export const GET_CATEGORYS = "GET_CATEGORYS";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORYS_LOADING = "CATEGORYS_LOADING";
export const SET_MODAL = "SET_MODAL";
