export const GET_CATEGORYS = "GET_CATEGORYS";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORYS_LOADING = "CATEGORYS_LOADING";
export const SET_MODAL = "SET_MODAL";
export const ADD_MODAL = "ADD_MODAL";
export const GET_SELLERS = "GET_SELLERS";
export const UPDATE_SELLER_LIST = "UPDATE_SELLER_LIST";
