export const GETPROFILE = "GETPROFILE";
export const UPDATEPROFILE = "UPDATEPROFILE";
export const UPDATEPROFILEPIC = "UPDATEPROFILEPIC";
export const ADDADDRESS='ADDADDRESS';
export const DELETEADDRESS='DELETEADDRESS';