export const GETPROFILE = "GETPROFILE";
export const UPDATEPROFILE = "UPDATEPROFILE";
export const UPDATEPROFILEPIC = "UPDATEPROFILEPIC";
export const ADDADDRESS = "ADDADDRESS";
export const DELETEADDRESS = "DELETEADDRESS";
export const GETPAYMENT = "GETPAYMENT";
export const ADDORUPDATEPAYMENT = "ADDORUPDATEPAYMENT";
export const DELETEPAYMENT = "ADDORUPDATEPAYMENT";
