export const GETSAVEDANDCARTPRODUCTS = "GETSAVEDANDCARTPRODUCTS";
export const DELETESAVEDPRODUCTS = "DELETESAVEDPRODUCTS";
export const MOVESAVEDTOCART = "MOVESAVEDTOCART";
export const ADDTOSAVEFORLATER = "ADDTOSAVEFORLATER";

export const DELETECARTPRODUCT = "DELETECARTPRODUCT";
export const MOVECARTTOSAVED = "MOVECARTTOSAVED";
export const UPDATECARTPRODUCT = "UPDATECARTPRODUCT";
export const ADDTOCART = "ADDTOCART";