export const GETSAVEDANDCARTPRODUCTS = "GETSAVEDANDCARTPRODUCTS";
export const DELETESAVEDPRODUCTS = "DELETESAVEDPRODUCTS";
export const MOVESAVEDTOCART = "MOVESAVEDTOCART";

export const DELETECARTPRODUCT = "DELETECARTPRODUCT";
export const MOVECARTTOSAVED = "MOVECARTTOSAVED";
