export const CATEGORY = "GETPRODUCTCATEGORY";
export const ALLPRODUCTS = "GETALLPRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_SEARCH = "SEARCH_PRODUCT";
export const PRODUCT_FILTER = "FILTER_PRODUCT";
export const PRODUCT_SORT = "SORT_PRODUCT";
export const ADDCOMMENT = "ADDCOMMENT";
export const DELETE_PRODUCT = "DELETEPRODUCT";
