export const GETSELLERORDERS='GETSELLERORDERS'
export const CANCELSELLERORDERPRODUCT='CANCELSELLERORDERPRODUCT'
export const GETOPENSELLERORDER='GETOPENSELLERORDER'

export const GETSELLERCANCELORDER='GETSELLERCANCELORDER'